# This is a basic workflow to help you get started with Actions

name: Add Headers

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Runs a single command using the runners shell
      - name: prepend data
        run: |
          wget https://github.com/alorman/dev-actions/blob/main/img/seamaster-1.jpg
          wget https://raw.githubusercontent.com/alorman/dev-actions/main/scripts/header.txt
          cat header.txt README.md > tempreadme.md
          echo "cat success"
          mv tempreadme.md README.md
          echo "move success"
      - name: Commit report
        run: |
          git config --global user.name 'robot'
          git config --global user.email 'robot@users.noreply.github.com'
          git commit -am "Automated report"
          git push
